apiVersion: v1
kind: Secret
metadata:
  name: iam-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  ORG_FACTORYX_LIBRARY_FXV01_VALIDATIONSERVICE_STSAPI: "dim-wallet"
  ORG_FACTORYX_LIBRARY_FXV01_VALIDATIONSERVICE_BEARER: "false"
  ORG_FACTORYX_LIBRARY_FXV01_VALIDATIONSERVICE_VAULTROOTTOKEN: "<path:factory-x-ci-cd/data/dsp-native-basyx#iam-vault-root-token>"
  ORG_FACTORYX_LIBRARY_FXV01_VALIDATIONSERVICE_VAULTSECRETALIAS: "<path:factory-x-ci-cd/data/dsp-native-basyx#iam-vault-secretalias>"
  ORG_FACTORYX_LIBRARY_FXV01_VALIDATIONSERVICE_DIMTOKENURL: "<path:factory-x-ci-cd/data/dsp-native-basyx#iam-dim-token-url>"
  ORG_FACTORYX_LIBRARY_FXV01_VALIDATIONSERVICE_DIMCLIENTID: "<path:factory-x-ci-cd/data/dsp-native-basyx#iam-dim-client-id>"
  ORG_FACTORYX_LIBRARY_FXV01_VALIDATIONSERVICE_DIMURL: "<path:factory-x-ci-cd/data/dsp-native-basyx#iam-dim-url>"
  ORG_FACTORYX_LIBRARY_ID: "<path:factory-x-ci-cd/data/dsp-native-basyx#iam-own-did>"
